export default {
    sliders: [
        {
            label: 'Basic Shape',
            key: 'basicShape',
            min: 1,
            init: 1,
            max: 4,
            step: 1,
            precision: 0,
        },
        {
            label: 'Basic Shape Size',
            key: 'basicShapeSize',
            min: 1,
            init: 1,
            max: 15,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Shape',
            key: 'screenSplitShape',
            min: 1,
            init: 1,
            max: 3,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Num',
            key: 'screenSplitNum',
            min: 1,
            init: 1,
            max: 12,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Split Spread',
            key: 'screenSplitSpread',
            min: 2,
            init: 4,
            max: 12,
            step: 1,
            precision: 0,
        },
        {
            label: 'Shape Hue',
            key: 'shapeHue',
            min: 0,
            init: 180,
            max: 360,
            step: 10,
            precision: 0,
        },
        {
            label: 'Screen Rotate Direction',
            key: 'screenRotateDirection',
            min: 1,
            init: 1,
            max: 2,
            step: 1,
            precision: 0,
        },
        {
            label: 'Screen Rotate Speed',
            key: 'screenRotateSpeed',
            min: 1,
            init: 1,
            max: 10,
            step: 0.1,
            precision: 0,
        },
    ],
};
